// каллории подсчитать, все из меню и цены перенести в mock, панель добавления продуктов
export const extras = [
    {
        name: "Lids",
        isActive: false,
        multipleSelectionAllowed: false,
        subCategories: [
            { name: "Standard", price: 0.50, svgPath: "svg/cup1.svg" },
            { name: "Sip Through", price: 0.75, svgPath: "svg/cup2.svg" },
            { name: "None", price: 0.00, svgPath: "svg/cup3.svg" },
        ],
    },
    {
        name: "Espresso Shot",
        isActive: false,
        subCategories: [
            { name: "Single Shot", price: 0.50, svgPath: "" },
            { name: "Double Shot", price: 1.00, svgPath: "" },
            { name: "Triple Shot", price: 1.50, svgPath: "" },
        ],
        multipleSelectionAllowed: false,
    },
    {
        name: "t°",
        isActive: false,
        subCategories: [
            { name: "Hot", price: 0.00, svgPath: "" },
            { name: "Warm", price: 0.00, svgPath: "" },
            { name: "Cold", price: 0.00, svgPath: "" },
            { name: "Iced", price: 0.00, svgPath: "" },
        ],
        multipleSelectionAllowed: false,
    },
    {
        name: "Milk",
        isActive: false,
        subCategories: [
            { name: "Almond", price: 0.75, svgPath: "" },
            { name: "Coconut", price: 0.75, svgPath: "" },
            { name: "Oat", price: 0.75, svgPath: "" },
            { name: "Whole", price: 0.00, svgPath: "" },
            { name: "Skimmed", price: 0.00, svgPath: "" },
            { name: "Splash of Milk", price: 0.00, svgPath: "" },
            { name: "Half & Half", price: 0.00, svgPath: "" },
            { name: "Heavy Cream", price: 0.00, svgPath: "" },
        ],
        multipleSelectionAllowed: false,
    },
    {
        name: "Sugar",
        isActive: false,
        subCategories: [
            { name: "Stevia", price: 0.00, svgPath: "svg/cup3.svg" },
            { name: "Brown Sugar", price: 0.00, svgPath: "svg/cup3.svg" },
            { name: "Honey", price: 0.25, svgPath: "svg/cup3.svg" },
            { name: "Splenda", price: 0.00, svgPath: "svg/cup3.svg" },
        ],
        multipleSelectionAllowed: true,
    },
    {
        name: "Syrup",
        isActive: false,
        subCategories: [
            { name: "Vanilla", price: 0.75, svgPath: "" },
            { name: "Caramel", price: 0.75, svgPath: "" },
            { name: "Hazelnut", price: 0.75, svgPath: "" },
            { name: "Almond", price: 0.75, svgPath: "" },
            { name: "Cherry", price: 0.75, svgPath: "" },
            { name: "Chocolate Milano", price: 0.75, svgPath: "" },
            { name: "Coconut", price: 0.75, svgPath: "" },
            { name: "Irish Cream", price: 0.75, svgPath: "" },
            { name: "Lavender Pump", price: 0.75, svgPath: "" },
            { name: "Mint", price: 0.75, svgPath: "" },
            { name: "Pineapple", price: 0.75, svgPath: "" },
            { name: "Raspberry", price: 0.75, svgPath: "" },
            { name: "Salted Caramel", price: 0.75, svgPath: "" },
            { name: "Toasted Marshmallow", price: 0.75, svgPath: "" },
            { name: "Vanilla Pump", price: 0.75, svgPath: "" },
            { name: "White Chocolate", price: 0.75, svgPath: "" },
            { name: "Hazelnut", price: 0.75, svgPath: "" },
            { name: "Sugar Free - Hazelnut", price: 0.75, svgPath: "" },
            { name: "Sugar Free - Salted Caramel", price: 0.75, svgPath: "" },
            { name: "Sugar Free - Vanilla", price: 0.75, svgPath: "" },

        ],
        multipleSelectionAllowed: true,
    },
    {
        name: "Toppings",
        isActive: false,
        subCategories: [
            { name: "Cardamom", price: 0.50, svgPath: "" },
            { name: "Chai Spices", price: 0.50, svgPath: "" },
            { name: "Cinnamon", price: 0.50, svgPath: "" },
            { name: "Lavender Vanilla Sugar", price: 0.50, svgPath: "" },
            { name: "Spiced Vanilla Sugar", price: 0.50, svgPath: "" },
            { name: "Saigon Cinnamon", price: 0.50, svgPath: "" },
            { name: "Turmeric", price: 0.50, svgPath: "" },
        ],
        multipleSelectionAllowed: true,
    },
];


export const kitchens = [
    { id: 1, name: "Drinks" },
    { id: 2, name: "Hot" },
    { id: 3, name: "Fryer" },
    { id: 4, name: "Cold" },
    { id: 4, name: "Salads" },
];

export const categories = [
    { name: "Hot Coffee", hash: "#hot_coffee", isActive: false, svgPath: "" },
    { name: "Cold Coffee", hash: "#cold_coffee", isActive: false, svgPath: "" },
    { name: "Tea", hash: "#tea", isActive: false, svgPath: "" },
    { name: "Hot Chocolate", hash: "#hot_chocolate", isActive: false, svgPath: "" },
    { name: "Sweet Bakery", hash: "#sweet_bakery", isActive: false, svgPath: "" },
    { name: "Savoury Bakery", hash: "#savoury_bakery", isActive: false, svgPath: "" },
    { name: "Specialty", hash: "#specialty", isActive: false, svgPath: "" },
];

export const data = {
    hot_coffee: [
        {
            id: 1,
            name: "Latte",
            price: 4.5,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 2,
            name: "Cappuccino",
            price: 4.5,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",

        },
        {
            id: 3,
            name: "Tinto",
            price: 3.0,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 4,
            name: "Americano",
            price: 3.75,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 5,
            name: "Espresso",
            price: 3.75,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 6,
            name: "Decaf",
            price: 3.0,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 7,
            name: "Cortado",
            price: 1.0,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 8,
            name: "Macchiato",
            price: 1.0,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 9,
            name: "Black Eye",
            price: 3.50,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 10,
            name: "Flat White",
            price: 4.50,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 11,
            name: "Cafe Con Leche",
            price: 3.75,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
    ],
    hot_chocolate: [
        {
            id: 12,
            name: "Milo Hot Chocolate",
            price: 4.5,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 13,
            name: "Milo Frio",
            price: 5.75,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 14,
            name: "Milo Frio Cold",
            price: 5.75,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 15,
            name: "Abuelita",
            price: 4.5,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
        {
            id: 16,
            name: "Abuelita Cold",
            price: 4.5,
            photo: "hot_coffee.png",
            videoSrc: "./live.mp4",
        },
    ],
    cold_coffee: [
        {
            id: 17,
            name: "Iced Coffee",
            price: 4.00,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",

        },
        {
            id: 18,
            name: "Iced Latte",
            price: 5.75,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 19,
            name: "Iced Matcha Latte",
            price: 5.75,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 20,
            name: "Iced Americano",
            price: 4.00,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 21,
            name: "Iced Espresso",
            price: 1.00,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 22,
            name: "Iced Black Eye",
            price: 3.50,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 23,
            name: "Cold Brew",
            price: 5.75,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 24,
            name: "Iced Coffee Lemonade",
            price: 5.75,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 25,
            name: "Espresso Tonic",
            price: 5.75,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
        {
            id: 26,
            name: "Iced Milo Latte",
            price: 5.75,
            photo: "cold_coffee.png",
            videoSrc: "./Ice_Latte.mp4",
        },
    ],
    tea: [
        {
            id: 27,
            name: "Chai Latte",
            price: 4.5,
            photo: "dessert_coffee.png",
            videoSrc: "./lemon_tart.mp4",
        },
        {
            id: 28,
            name: "Chai Latte Iced",
            price: 4.5,
            photo: "dessert_coffee.png",
            videoSrc: "./lemon_tart.mp4",
        },
        {
            id: 29,
            name: "Matcha Latte",
            price: 4.5,
            photo: "dessert_coffee.png",
            videoSrc: "./lemon_tart.mp4",
        },
        {
            id: 30,
            name: "Matcha Latte Iced",
            price: 4.5,
            photo: "dessert_coffee.png",
            videoSrc: "./lemon_tart.mp4",
        },
        {
            id: 31,
            name: "Hot Tea",
            price: 0.3,
            photo: "dessert_coffee.png",
            videoSrc: "./lemon_tart.mp4",
        },
    ],
    sweet_bakery: [
        {
            id: 32,
            name: "Butter Croissant",
            price: 4.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 33,
            name: "Chocolate Croissant",
            price: 4.25,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 34,
            name: "Seasonal Galette",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 35,
            name: "Orange Earl Grey Sconce",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 36,
            name: "Pan De Bono Con Guava",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 37,
            name: "Churros",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 38,
            name: "Almond Croissant",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 39,
            name: "Special Cookies",
            price: 3.75,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 40,
            name: "Banana Bread",
            price: 3.75,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 41,
            name: "White Chocolate Cranberry Muffins",
            price: 3.75,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
    ],
    savoury_bakery: [
        {
            id: 42,
            name: "Ham & Cheese Croissant",
            price: 5.25,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",

        },
        {
            id: 43,
            name: "Spinach Mushroom Buddy",
            price: 4.5,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 44,
            name: "Almojabana",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 45,
            name: "Ground Beef Empanadas",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
        {
            id: 46,
            name: "Chicken Empanadas",
            price: 3.0,
            photo: "dessert_coffee.png",
            videoSrc: "./bakery.mp4",
        },
    ],
    specialty: [
        {
            id: 47,
            name: "House Roast",
            price: 16.0,
            photo: "dessert_coffee.png",
            videoSrc: "./specialty.mp4",
        },
        {
            id: 48,
            name: "Las Cascadas",
            price: 16.0,
            photo: "dessert_coffee.png",
            videoSrc: "./specialty.mp4",
        },
        {
            id: 49,
            name: "House Decaf",
            price: 16.0,
            photo: "dessert_coffee.png",
            videoSrc: "./specialty.mp4",
        },
        {
            id: 50,
            name: "House Espresso",
            price: 16.0,
            photo: "dessert_coffee.png",
            videoSrc: "./specialty.mp4",
        },
        {
            id: 51,
            name: "Finca Verona",
            price: 16.0,
            photo: "dessert_coffee.png",
            videoSrc: "./specialty.mp4",
        },
        {
            id: 52,
            name: "Guayacao",
            price: 16.0,
            photo: "dessert_coffee.png",
            videoSrc: "./specialty.mp4",
        },
        {
            id: 53,
            name: "Santa Maria",
            price: 16.0,
            photo: "dessert_coffee.png",
            videoSrc: "./specialty.mp4",
        },
    ],
};
